### ISSUE TITLE
Using the same -a address for the webui

### ISSUE THREAD

**Issue by madflow** [aaronvb/request_hole#9]
Hi there. This looks like a very useful tool! 

I was checking out the possibility to use this in a "review app" running in a Docker environment. But:

`
rh http -a 0.0.0.0 --web
` 

only binds the backend server to the address (-a) and not the web ui. Is this something you would consider changing?

```
┌───────────────────────────────────────┐
| Request Hole 1.0.1                    |
| Listening on http://0.0.0.0:8080      |
| Web running on: http://localhost:8081 |
└───────────────────────────────────────┘
```

Maybe there is something else I can do here, dunno...

**Comment by aaronvb** [comment]
@madflow good catch and thanks for the feedback! 

I agree, there should be a flag option to bind the web UI address. I'll work on adding this in the next few days.

**Comment by aaronvb** [comment]
You can now pass the `--web_address` flag to bind the web UI address. Hope this helps!

**Comment by madflow** [comment]
Perfect! Working know in Docker, too.
